opBasic = function(a,b){
  print("Suma")
  print(a+b)
  print("Resta")
  print(paste(sprintf("%i - %i = ",a,b),a-b))
  print(paste(sprintf("%i - %i = ",b,a),b-a))
  print("Multiplicación")
  print(a*b)
  print("División")
  print(paste(sprintf("%i / %i = ",a,b),a/b))
  print(paste(sprintf("%i / %i = ",b,a),b/a))
  print("Cosciente entero")
  print(paste(sprintf("%i : %i = ",a,b),a%/%b))
  print(paste(sprintf("%i : %i = ",b,a),b%/%a))
  print("Resto")
  print(paste(sprintf("%i : %i = ",a,b),a%%b))
  print(paste(sprintf("%i : %i = ",b,a),b%%a))
}

opBasic(4,6)
